import time
from playsound import playsound
print("These are all the things that I can do:")
print("///////////////////////////////////////////////////")
print("what's is the weather")
print("what is the weather")
print("weather")
print("a (game)")
print("b (set a reminder)")
print("c (weather)")
print("d (calculator)")
print("e (convert text to speech)")
print("f (more info)")
print("Play a game")
print("Set a reminder")
print("Open calculator")
print("game")
print("play")
print("reminder")
print("calculator")
print("Convert text to speech")
print("text to speech")
print("more info")
print("info")
print("more")
print("goodbye")
print("bye")
print("hi")
print("hello")
print("tell me a joke")
print("tell a joke")
print("make me laugh")
print("///////////////////////////////////////////////////")

playsound('Smart_Assistant/Sound/info.mp3')
time.sleep(.5)
import main