import time
from playsound import playsound
import os
os.system('CLS')

print("These are all the things that I can do:")
print("///////////////////////////////////////////////////")
print("what's is the weather")
print("what is the weather")
print("weather")
print("Play a game")
print("Set a reminder")
print("Open calculator")
print("game")
print("play")
print("reminder")
print("calculator")
print("Convert text to speech")
print("text to speech")
print("more info")
print("info")
print("more")
print("goodbye")
print("bye")
print("hi")
print("hello")
print("tell me a joke")
print("tell a joke")
print("make me laugh")
print("I would like to play a game")
print("I want to play a game")
print("Could you please set a reminder")
print("I would like to set a reminder")
print("I want to set a reminder")
print("can you please open the calculator")
print("///////////////////////////////////////////////////")

playsound('Smart_Assistant/Sound/info.mp3')
time.sleep(.5)
import command